"use client";

import { useMemo, useState, type FormEvent } from "react";
import { BookOpen, Copy, Download, Edit3, Heart, Play, Plus, Search, Star, Trash2 } from "lucide-react";
import { promptSeeds, type PromptRecord } from "@/lib/prompts";
import { Modal } from "./Modal";
import { useLocalState } from "@/lib/use-local-state";

interface KnowledgeRecord {
  id: string; title: string; category: string; scene: string; content: string; favorite: boolean; updatedAt: string;
}

const promptTypes = ["全部", "扩写要求", "拆书要求", "续写要求", "写作风格", "写作要求", "书名生成器", "简介生成器", "细纲生成器", "大纲生成器", "黄金开篇生成器", "人设生成器", "世界观生成器", "审稿要求", "词条生成器", "剧本医生", "去痕要求"];
const promptCategories = ["全部", "长篇", "短篇", "老福特", "短剧", "剧本", "降AI率", "我的"];

export function PromptLibraryPage({ onRun }: { onRun: (name: string, prompt?: string) => void }) {
  const [records, setRecords] = useLocalState<PromptRecord[]>("xingyue-prompts", promptSeeds);
  const [query, setQuery] = useState(""); const [type, setType] = useState("全部"); const [category, setCategory] = useState("全部"); const [sort, setSort] = useState("最热");
  const [editing, setEditing] = useState<PromptRecord | null>(null); const [viewing, setViewing] = useState<PromptRecord | null>(null);
  const filtered = useMemo(() => records.filter(item => (type === "全部" || item.type === type) && (category === "全部" || category === "我的" && item.owned || item.category === category) && (!query || `${item.title}${item.description}${item.content}`.toLowerCase().includes(query.toLowerCase())) && (sort !== "已收藏" || item.favorite)).sort((a,b) => sort === "最新" ? b.updatedAt.localeCompare(a.updatedAt) : b.uses - a.uses), [records,type,category,query,sort]);

  function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing?.title.trim() || !editing.content.trim()) return;
    const item = { ...editing, title: editing.title.trim(), description: editing.description.trim(), content: editing.content.trim(), owned: true, updatedAt: new Date().toISOString().slice(0,10) };
    setRecords(current => current.some(record => record.id === item.id) ? current.map(record => record.id === item.id ? item : record) : [item,...current]); setEditing(null);
  }
  function remove(item: PromptRecord) { if (!item.owned || !confirm(`删除提示词“${item.title}”？`)) return; setRecords(records.filter(record => record.id !== item.id)); setViewing(null); }
  async function copyText(text: string) { try { await navigator.clipboard.writeText(text); } catch { /* Text remains selectable in preview. */ } }

  return <section className="market-page" aria-label="提示词市场">
    <aside className="market-categories"><strong>提示词分类</strong>{promptTypes.map(item => <button key={item} className={type === item ? "active" : ""} onClick={() => setType(item)}>{item}</button>)}</aside>
    <div className="market-main"><header className="market-heading"><div><h2>提示词</h2><p>管理、收藏并运行你的写作提示词</p></div><button className="primary-button" onClick={() => setEditing({ id: crypto.randomUUID(), title: "", type: "写作要求", category: "长篇", content: "", description: "", uses: 0, favorite: false, owned: true, updatedAt: "" })}><Plus size={15} />新建提示词</button></header>
      <div className="market-search"><label><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索全部提示词..." aria-label="搜索全部提示词" /></label></div>
      <div className="market-filters"><span>分类筛选</span>{promptCategories.map(item => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}<span className="market-filter-gap" />{["最热","精选","最新","已收藏"].map(item => <button key={item} className={sort === item ? "active" : ""} onClick={() => setSort(item)}>{item}</button>)}</div>
      <div className="prompt-list">{filtered.map(item => <article className="prompt-card" key={item.id}><div className="prompt-card-top"><span>{item.type}</span><button aria-label={item.favorite ? "取消收藏" : "收藏"} onClick={() => setRecords(records.map(record => record.id === item.id ? { ...record, favorite: !record.favorite } : record))}><Heart size={16} fill={item.favorite ? "currentColor" : "none"} /></button></div><button className="prompt-card-body" onClick={() => setViewing(item)}><h3>{item.title}</h3><p>{item.description}</p><small>{item.content}</small></button><footer><span>{item.category} · {item.updatedAt}</span><span>{item.uses} 次使用</span><button className="primary-button" onClick={() => { setRecords(records.map(record => record.id === item.id ? { ...record, uses: record.uses + 1 } : record)); onRun(item.title,item.content); }}><Play size={13} />运行</button></footer></article>)}</div>
      {!filtered.length && <div className="page-empty"><Search size={32} /><p>没有符合条件的提示词</p><button className="subtle-button" onClick={() => { setQuery(""); setType("全部"); setCategory("全部"); setSort("最热"); }}>清除筛选</button></div>}
    </div>
    {editing && <Modal title={records.some(item => item.id === editing.id) ? "编辑提示词" : "新建提示词"} onClose={() => setEditing(null)} wide><form className="record-form" onSubmit={save}><label>名称<input className="form-input" required maxLength={50} value={editing.title} onChange={event => setEditing({ ...editing,title:event.target.value })} /></label><div className="record-form-row"><label>类型<select className="form-input" value={editing.type} onChange={event => setEditing({ ...editing,type:event.target.value })}>{promptTypes.filter(item => item !== "全部").map(item => <option key={item}>{item}</option>)}</select></label><label>分类<select className="form-input" value={editing.category} onChange={event => setEditing({ ...editing,category:event.target.value })}>{promptCategories.filter(item => item !== "全部" && item !== "我的").map(item => <option key={item}>{item}</option>)}</select></label></div><label>简介<textarea className="form-input min-h-20" maxLength={200} value={editing.description} onChange={event => setEditing({ ...editing,description:event.target.value })} /></label><label>提示词内容<textarea className="form-input min-h-64" required maxLength={12000} value={editing.content} onChange={event => setEditing({ ...editing,content:event.target.value })} /></label><div className="record-actions"><button type="button" className="subtle-button" onClick={() => setEditing(null)}>取消</button><button className="primary-button">保存</button></div></form></Modal>}
    {viewing && <Modal title={viewing.title} onClose={() => setViewing(null)} wide><div className="record-preview"><div className="flex flex-wrap gap-2"><span className="tag-chip">{viewing.type}</span><span className="tag-chip">{viewing.category}</span>{viewing.favorite && <span className="tag-chip"><Star size={12} />已收藏</span>}</div><p>{viewing.description}</p><textarea className="form-input min-h-72" readOnly value={viewing.content} /><div className="record-actions"><button className="subtle-button" onClick={() => copyText(viewing.content)}><Copy size={14} />复制</button>{viewing.owned && <><button className="subtle-button" onClick={() => { setEditing(viewing); setViewing(null); }}><Edit3 size={14} />编辑</button><button className="subtle-button text-red-600" onClick={() => remove(viewing)}><Trash2 size={14} />删除</button></>}<button className="primary-button" onClick={() => onRun(viewing.title,viewing.content)}><Play size={14} />运行</button></div></div></Modal>}
  </section>;
}

const emptyKnowledge: KnowledgeRecord[] = [];
const knowledgeCategories = ["全部","写作风格","世界观","角色规范","术语规则","示例片段","其他"];

export function KnowledgePage() {
  const [records,setRecords] = useLocalState<KnowledgeRecord[]>("xingyue-knowledge-cards",emptyKnowledge);
  const [query,setQuery] = useState(""); const [category,setCategory] = useState("全部"); const [sort,setSort] = useState("我的"); const [editing,setEditing] = useState<KnowledgeRecord|null>(null); const [viewing,setViewing] = useState<KnowledgeRecord|null>(null);
  const filtered = records.filter(item => (category === "全部" || item.category === category) && (!query || `${item.title}${item.scene}${item.content}`.toLowerCase().includes(query.toLowerCase())) && (sort !== "已收藏" || item.favorite)).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt));
  function save(event: FormEvent) { event.preventDefault(); if (!editing?.title.trim() || !editing.content.trim()) return; const item={...editing,title:editing.title.trim(),content:editing.content.trim(),updatedAt:new Date().toISOString()}; setRecords(current => current.some(record=>record.id===item.id)?current.map(record=>record.id===item.id?item:record):[item,...current]); setEditing(null); }
  function download(item: KnowledgeRecord) { const url=URL.createObjectURL(new Blob([`${item.title}\n\n${item.content}`],{type:"text/markdown;charset=utf-8"})); const link=document.createElement("a");link.href=url;link.download=`${item.title}.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
  return <section className="knowledge-page"><header className="market-heading"><div><h2>知识卡</h2><h3>小说知识卡</h3><p>沉淀风格、术语、规范和示例，写作时可作为 AI 上下文。</p></div><button className="primary-button" onClick={() => setEditing({id:crypto.randomUUID(),title:"",category:"写作风格",scene:"",content:"",favorite:false,updatedAt:""})}><Plus size={15}/>新建知识卡</button></header><div className="knowledge-toolbar"><label><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索知识卡..."/></label><select value={category} onChange={event=>setCategory(event.target.value)}>{knowledgeCategories.map(item=><option key={item}>{item}</option>)}</select>{["我的","最新","已收藏"].map(item=><button className={sort===item?"active":""} key={item} onClick={()=>setSort(item)}>{item}</button>)}</div>
    <div className="knowledge-grid">{filtered.map(item=><article className="knowledge-card" key={item.id}><div><span>{item.category}</span><button aria-label={item.favorite?"取消收藏":"收藏"} onClick={()=>setRecords(records.map(record=>record.id===item.id?{...record,favorite:!record.favorite}:record))}><Heart size={16} fill={item.favorite?"currentColor":"none"}/></button></div><button onClick={()=>setViewing(item)}><h3>{item.title}</h3><p>{item.content}</p></button><footer><span>{item.scene||"通用场景"}</span><span>{item.content.replace(/\s/g,"").length} 字</span></footer></article>)}</div>
    {!filtered.length && <div className="page-empty"><BookOpen size={40}/><h3>还没有知识卡</h3><p>把常用的风格、设定和术语保存下来，后续生成时可随时关联。</p><button className="primary-button" onClick={()=>setEditing({id:crypto.randomUUID(),title:"",category:"写作风格",scene:"",content:"",favorite:false,updatedAt:""})}><Plus size={14}/>创建第一张知识卡</button></div>}
    {editing&&<Modal title={records.some(item=>item.id===editing.id)?"编辑知识卡":"新建知识卡"} onClose={()=>setEditing(null)} wide><form className="record-form" onSubmit={save}><label>标题<input autoFocus required className="form-input" maxLength={60} value={editing.title} onChange={event=>setEditing({...editing,title:event.target.value})}/></label><div className="record-form-row"><label>分类<select className="form-input" value={editing.category} onChange={event=>setEditing({...editing,category:event.target.value})}>{knowledgeCategories.filter(item=>item!=="全部").map(item=><option key={item}>{item}</option>)}</select></label><label>使用场景<input className="form-input" maxLength={80} placeholder="例如：都市题材对白" value={editing.scene} onChange={event=>setEditing({...editing,scene:event.target.value})}/></label></div><label>知识内容<textarea required className="form-input min-h-80" maxLength={20000} value={editing.content} onChange={event=>setEditing({...editing,content:event.target.value})}/></label><div className="record-actions"><button type="button" className="subtle-button" onClick={()=>setEditing(null)}>取消</button><button className="primary-button">保存知识卡</button></div></form></Modal>}
    {viewing&&<Modal title={viewing.title} onClose={()=>setViewing(null)} wide><div className="record-preview"><div className="flex gap-2"><span className="tag-chip">{viewing.category}</span><span className="tag-chip">{viewing.scene||"通用场景"}</span></div><textarea className="form-input min-h-80" readOnly value={viewing.content}/><div className="record-actions"><button className="subtle-button" onClick={()=>navigator.clipboard.writeText(viewing.content).catch(()=>{})}><Copy size={14}/>复制</button><button className="subtle-button" onClick={()=>download(viewing)}><Download size={14}/>导出</button><button className="subtle-button" onClick={()=>{setEditing(viewing);setViewing(null);}}><Edit3 size={14}/>编辑</button><button className="subtle-button text-red-600" onClick={()=>{if(confirm(`删除知识卡“${viewing.title}”？`)){setRecords(records.filter(item=>item.id!==viewing.id));setViewing(null);}}}><Trash2 size={14}/>删除</button></div></div></Modal>}
  </section>;
}
